"""
Report service — generates the full structured meeting report.

Why a dedicated service for reports:
- Aggregates data from both the DB (summary) and computed fields (Markdown rendering)
- Keeps the route handler thin
- The Markdown report is a portfolio-friendly deliverable — shareable, readable, importable into Notion/Confluence
"""
import json
from datetime import datetime, timezone

from app.config.logging import get_logger
from app.services.meeting_service import get_meeting

logger = get_logger(__name__)


def _priority_badge(priority: str) -> str:
    """Convert priority string to emoji badge for Markdown readability."""
    return {"high": "🔴", "medium": "🟡", "low": "🟢",
            "must-have": "🔴", "should-have": "🟡", "nice-to-have": "🟢"}.get(
        priority.lower(), "⚪"
    )


def _severity_badge(severity: str) -> str:
    return {"high": "🔴", "medium": "🟡", "low": "🟢"}.get(severity.lower(), "⚪")


def _format_markdown_report(meeting_id: str, title: str, transcript: str, summary) -> str:
    """
    Render the full meeting analysis as a clean Markdown document.

    This is the human-readable output — shareable with teams, importable into
    Notion, Confluence, or any Markdown-aware tool.
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        f"# Meeting Report",
        f"",
        f"**Title:** {title or 'Untitled Meeting'}  ",
        f"**Meeting ID:** `{meeting_id}`  ",
        f"**Generated:** {now}",
        f"",
        f"---",
        f"",
        f"## 📝 Summary",
        f"",
        f"{summary.summary}",
        f"",
    ]

    # Key Topics
    if summary.key_topics:
        lines += ["## 🎯 Key Topics", ""]
        for topic in summary.key_topics:
            lines.append(f"- {topic}")
        lines.append("")

    # Decisions
    if summary.decisions:
        lines += ["## ✅ Decisions Made", ""]
        for decision in summary.decisions:
            lines.append(f"- {decision}")
        lines.append("")

    # Participants
    if summary.participants:
        lines += ["## 👥 Participants", ""]
        lines.append(", ".join(f"**{p}**" for p in summary.participants))
        lines.append("")

    # Action Items
    lines += ["## 📋 Action Items", ""]
    if summary.action_items:
        lines.append("| # | Task | Owner | Deadline | Priority |")
        lines.append("|---|------|-------|----------|----------|")
        for i, item in enumerate(summary.action_items, 1):
            badge = _priority_badge(item.get("priority", "medium"))
            lines.append(
                f"| {i} | {item.get('task', '')} | {item.get('owner', 'Unassigned')} "
                f"| {item.get('deadline', 'TBD')} | {badge} {item.get('priority', '')} |"
            )
    else:
        lines.append("_No action items identified._")
    lines.append("")

    # Requirements
    lines += ["## 📦 Requirements", ""]
    if summary.requirements:
        lines.append("| Requirement | Category | Priority |")
        lines.append("|-------------|----------|----------|")
        for req in summary.requirements:
            badge = _priority_badge(req.get("priority", "should-have"))
            lines.append(
                f"| {req.get('requirement', '')} | `{req.get('category', '')}` "
                f"| {badge} {req.get('priority', '')} |"
            )
    else:
        lines.append("_No specific requirements extracted._")
    lines.append("")

    # Risks
    lines += ["## ⚠️ Risks & Blockers", ""]
    if summary.risks:
        for risk in summary.risks:
            badge = _severity_badge(risk.get("severity", "low"))
            lines.append(f"### {badge} {risk.get('risk', '')}")
            lines.append(f"- **Severity:** {risk.get('severity', 'unknown')}")
            lines.append(f"- **Mitigation:** {risk.get('mitigation_suggestion', 'None specified')}")
            lines.append("")
    else:
        lines.append("_No risks identified._")
        lines.append("")

    lines += [
        "---",
        f"*Generated by Meeting-to-Action Agent · {now}*",
    ]

    return "\n".join(lines)


async def generate_report(meeting_id: str) -> dict:
    """
    Generate a full meeting report as both Markdown and structured JSON.

    Returns dict with:
        - markdown: str — human-readable Markdown report
        - json_data: dict — machine-readable structured data
        - meeting_id: str
        - title: str
    """
    meeting = await get_meeting(meeting_id)
    if meeting is None:
        return None

    if meeting.summary is None:
        return {
            "meeting_id": meeting_id,
            "title": meeting.title,
            "status": "not_summarised",
            "error": "This meeting has not been summarised yet. Call POST /meetings/{id}/summarise first.",
            "markdown": None,
            "json_data": None,
        }

    markdown = _format_markdown_report(
        meeting_id=meeting_id,
        title=meeting.title or "Untitled Meeting",
        transcript=meeting.transcript,
        summary=meeting.summary,
    )

    json_data = {
        "meeting_id": meeting_id,
        "title": meeting.title,
        "summary": meeting.summary.summary,
        "key_topics": meeting.summary.key_topics,
        "decisions": meeting.summary.decisions,
        "participants": meeting.summary.participants,
        "action_items": meeting.summary.action_items,
        "requirements": meeting.summary.requirements,
        "risks": meeting.summary.risks,
    }

    return {
        "meeting_id": meeting_id,
        "title": meeting.title,
        "status": "ready",
        "markdown": markdown,
        "json_data": json_data,
    }
